//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    [System.Flags]
    public enum CreatureType
    {
        /// <summary>
        /// 城堡
        /// </summary>
        Castle = 0,
        /// <summary>
        /// 小人
        /// </summary>
        Role = 1,
        /// <summary>
        /// 小怪
        /// </summary>
        Enemy = 2,
        /// <summary>
        /// boss
        /// </summary>
        Boss = 3,
        /// <summary>
        /// 宝箱
        /// </summary>
        Treasure = 4,
    }

} 
