//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum EnAttr
    {
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1001,
        /// <summary>
        /// 攻击
        /// </summary>
        Atk = 1002,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSpeed = 1003,
        /// <summary>
        /// 半径
        /// </summary>
        Radius = 1004,
    }

} 
