//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class FootHold: Bright.Config.BeanBase
{
    public FootHold(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SpawnIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SpawnIds.Add(_e0);}}
        PostInit();
    }

    public static FootHold DeserializeFootHold(ByteBuf _buf)
    {
        return new FootHold(_buf);
    }

    public int Id { get; private set; }
    public string Name { get; private set; }
    /// <summary>
    /// SpawnConfig中的Id
    /// </summary>
    public System.Collections.Generic.List<int> SpawnIds { get; private set; }

    public const int __ID__ = 458551917;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "SpawnIds:" + Bright.Common.StringUtil.CollectionToString(SpawnIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}