//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    [System.Flags]
    public enum SpellKey
    {
        AddAttr = 0,
        NormalBullet = 1,
        EnemyAtk = 2,
    }

} 
