//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class FootHoldCategory: ConfigSingleton<FootHoldCategory>
{
    private readonly Dictionary<int, FootHold> _dataMap;
    private readonly List<FootHold> _dataList;
    
    public FootHoldCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, FootHold>();
        _dataList = new List<FootHold>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FootHold _v;
            _v = FootHold.DeserializeFootHold(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, FootHold> GetAll()
    {
        return _dataMap;
    }
    
    public List<FootHold> DataList => _dataList;

    public FootHold GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FootHold Get(int key) => _dataMap[key];
    public FootHold this[int key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(FootHold).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}