//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    [System.Flags]
    public enum DropConfigScript
    {
        None = 0,
        Exp = 1,
        Power = 2,
    }

} 
