//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum EnAttr
    {
        MaxHp = 0,
        Atk = 1,
        MoveSpeed = 2,
    }

} 
