//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class SpawnConfig: Bright.Config.BeanBase
{
    public SpawnConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DelayTime = _buf.ReadInt();
        Interval = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CreatureIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CreatureIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);CreatureCount = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CreatureCount.Add(_e0);}}
        PostInit();
    }

    public static SpawnConfig DeserializeSpawnConfig(ByteBuf _buf)
    {
        return new SpawnConfig(_buf);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 延迟
    /// </summary>
    public int DelayTime { get; private set; }
    /// <summary>
    /// 间隔
    /// </summary>
    public int Interval { get; private set; }
    /// <summary>
    /// 生物id
    /// </summary>
    public System.Collections.Generic.List<int> CreatureIds { get; private set; }
    public System.Collections.Generic.List<int> CreatureCount { get; private set; }

    public const int __ID__ = -780975491;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DelayTime:" + DelayTime + ","
        + "Interval:" + Interval + ","
        + "CreatureIds:" + Bright.Common.StringUtil.CollectionToString(CreatureIds) + ","
        + "CreatureCount:" + Bright.Common.StringUtil.CollectionToString(CreatureCount) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}